--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      UNAM
-- Project :      NetMag.DM1
-- Author :       Ivan Tagle
--
-- Date Created : Thursday, December 08, 2016 12:09:50
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: "AREA DE INTERES" 
--

CREATE TABLE "AREA DE INTERES"(
    "AREA DE INT_ID"  NUMBER(40, 0)    NOT NULL,
    DESCRIPCION       VARCHAR2(40)     NOT NULL,
    NOMBRE            VARCHAR2(40)     NOT NULL,
    CLAVE             VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK3 PRIMARY KEY ("AREA DE INT_ID")
)
;



-- 
-- TABLE: AREA_REVISOR 
--

CREATE TABLE AREA_REVISOR(
    AREA_REVISOR_ID    NUMBER(40, 0)    NOT NULL,
    AÑOS_EXP           NUMBER(40, 0)    NOT NULL,
    EMPLEADO_ID        NUMBER(40, 0)    NOT NULL,
    "AREA DE INT_ID"   NUMBER(40, 0)    NOT NULL,
    CONSTRAINT PK14 PRIMARY KEY (AREA_REVISOR_ID)
)
;



-- 
-- TABLE: ARTICULO 
--

CREATE TABLE ARTICULO(
    ARTICULO_ID       NUMBER(40, 0)    NOT NULL,
    FOLIO             VARCHAR2(18)     NOT NULL,
    TITULO            VARCHAR2(40)     NOT NULL,
    SINOPSIS          VARCHAR2(40)     NOT NULL,
    "AREA DE INT_ID"  NUMBER(40, 0)    NOT NULL,
    EDITOR_ID         NUMBER(40, 0),
    STATUS_ID         NUMBER(40, 0)    NOT NULL,
    CONSTRAINT PK2 PRIMARY KEY (ARTICULO_ID)
)
;



-- 
-- TABLE: AUTOR 
--

CREATE TABLE AUTOR(
    AUTOR_ID            NUMBER(40, 0)    NOT NULL,
    OCUPACION           VARCHAR2(40)     NOT NULL,
    INSTITUCION         VARCHAR2(40)     NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    APELLIDO_PATERNO    VARCHAR2(40)     NOT NULL,
    APELLIDO_MATERNO    VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK1 PRIMARY KEY (AUTOR_ID)
)
;



-- 
-- TABLE: AUTOR_ARTICULO 
--

CREATE TABLE AUTOR_ARTICULO(
    AUTOR_ARTICULO_ID    NUMBER(40, 0)    NOT NULL,
    AUTOR_ID             NUMBER(40, 0)    NOT NULL,
    ARTICULO_ID          NUMBER(40, 0)    NOT NULL,
    CONSTRAINT PK4 PRIMARY KEY (AUTOR_ARTICULO_ID)
)
;



-- 
-- TABLE: EDITOR 
--

CREATE TABLE EDITOR(
    EMPLEADO_ID    NUMBER(40, 0)    NOT NULL,
    GRADO          VARCHAR2(40)     NOT NULL,
    EMAIL          VARCHAR2(40)     NOT NULL,
    #CEDULA        NUMBER(40, 0)    NOT NULL,
    CONSTRAINT PK12 PRIMARY KEY (EMPLEADO_ID)
)
;



-- 
-- TABLE: EMPLEADO 
--

CREATE TABLE EMPLEADO(
    EMPLEADO_ID      NUMBER(40, 0)    NOT NULL,
    ES_REVISOR       NUMBER(1, 0)     NOT NULL,
    ES_EDITOR        NUMBER(1, 0)     NOT NULL,
    NOMBRE           VARCHAR2(40)     NOT NULL,
    APELLIDO_PAT     VARCHAR2(40)     NOT NULL,
    APELLIDO_MAT     VARCHAR2(40)     NOT NULL,
    FECHA_INGRESO    DATE             NOT NULL,
    CONSTRAINT PK10 PRIMARY KEY (EMPLEADO_ID)
)
;



-- 
-- TABLE: HISTORICO 
--

CREATE TABLE HISTORICO(
    HISTORICO      NUMBER(40, 0)    NOT NULL,
    STATUS_ID      NUMBER(40, 0)    NOT NULL,
    ARTICULO_ID    NUMBER(40, 0)    NOT NULL,
    CONSTRAINT PK21 PRIMARY KEY (HISTORICO)
)
;



-- 
-- TABLE: PDF 
--

CREATE TABLE PDF(
    PDF_ID         NUMBER(40, 0)    NOT NULL,
    ARCHIVO        BLOB             NOT NULL,
    DESCRIPCION    VARCHAR2(140)    NOT NULL,
    CLAVE          VARCHAR2(40)     NOT NULL,
    ARTICULO_ID    NUMBER(40, 0)    NOT NULL,
    CONSTRAINT PK6 PRIMARY KEY (PDF_ID)
)
;



-- 
-- TABLE: PUBLICACION 
--

CREATE TABLE PUBLICACION(
    PUBLICACION_ID    NUMBER(40, 0)    NOT NULL,
    BIMESTRE          VARCHAR2(40)     NOT NULL,
    FECHA             DATE             NOT NULL,
    TITULO            VARCHAR2(40)     NOT NULL,
    #VENDIDOS         NUMBER(40, 0)    NOT NULL,
    AÑO               NUMBER(40, 0)    NOT NULL,
    #GENERADOR        NUMBER(40, 0)    NOT NULL,
    CONSTRAINT PK7 PRIMARY KEY (PUBLICACION_ID)
)
;



-- 
-- TABLE: PUBLICACION_ARTICULO 
--

CREATE TABLE PUBLICACION_ARTICULO(
    PUBLIC_ART_ID     NUMBER(40, 0)    NOT NULL,
    ARTICULO_ID       NUMBER(40, 0)    NOT NULL,
    PUBLICACION_ID    NUMBER(40, 0)    NOT NULL,
    NUM_PAGINA        NUMBER(40, 0)    NOT NULL,
    CONSTRAINT PK8 PRIMARY KEY (PUBLIC_ART_ID)
)
;



-- 
-- TABLE: PUBLICACION_SUSCRIPTOR 
--

CREATE TABLE PUBLICACION_SUSCRIPTOR(
    PUBLICACION_SUSCRIPTOR_ID    CHAR(40)         NOT NULL,
    SUSCRIPTOR_ID                NUMBER(40, 0)    NOT NULL,
    PUBLICACION_ID               NUMBER(40, 0)    NOT NULL,
    FECHA_ENVIO                  DATE             NOT NULL,
    CONSTRAINT PK18 PRIMARY KEY (PUBLICACION_SUSCRIPTOR_ID)
)
;



-- 
-- TABLE: REVISADO_ARTICULO 
--

CREATE TABLE REVISADO_ARTICULO(
    REVISADO_ARTICULO_ID    NUMBER(40, 0)    NOT NULL,
    NOTIFICACION            BLOB,
    CALIFICACION            NUMBER(40, 0),
    REVISOR_ID              NUMBER(40, 0),
    ARTICULO_ID             NUMBER(40, 0)    NOT NULL,
    CONSTRAINT PK15 PRIMARY KEY (REVISADO_ARTICULO_ID)
)
;



-- 
-- TABLE: REVISOR 
--

CREATE TABLE REVISOR(
    EMPLEADO_ID     NUMBER(40, 0)    NOT NULL,
    #CONTRATO       NUMBER(40, 0)    NOT NULL,
    EMAIL           VARCHAR2(40),
    FIN_CONTRATO    DATE             NOT NULL,
    CONSTRAINT PK13 PRIMARY KEY (EMPLEADO_ID)
)
;



-- 
-- TABLE: STATUS 
--

CREATE TABLE STATUS(
    STATUS_ID    NUMBER(40, 0)    NOT NULL,
    NOMBRE       VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK20 PRIMARY KEY (STATUS_ID)
)
;



-- 
-- TABLE: SUSCRIPTOR 
--

CREATE TABLE SUSCRIPTOR(
    SUSCRIPTOR_ID             NUMBER(40, 0)    NOT NULL,
    NOMBRE                    VARCHAR2(40)     NOT NULL,
    "APELLIDO MATERNO"        VARCHAR2(40)     NOT NULL,
    "FECHA DE SUSCRIPCION"    DATE             NOT NULL,
    EMAIL                     VARCHAR2(40)     NOT NULL,
    "APELLIDO PATERNO"        VARCHAR2(40)     NOT NULL,
    "DURACION A LA VIGENCIA"  VARCHAR2(40)     NOT NULL,
    CALLE                     VARCHAR2(40)     NOT NULL,
    NUMERO                    NUMBER(40, 0)    NOT NULL,
    COLONIA                   VARCHAR2(40)     NOT NULL,
    CODIGO_POSTAL             NUMBER(40, 0)    NOT NULL,
    DELEGACION_MUNICIPIO      VARCHAR2(40)     NOT NULL,
    ESTADO                    VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK17 PRIMARY KEY (SUSCRIPTOR_ID)
)
;



-- 
-- TABLE: AREA_REVISOR 
--

ALTER TABLE AREA_REVISOR ADD CONSTRAINT RefREVISOR15 
    FOREIGN KEY (EMPLEADO_ID)
    REFERENCES REVISOR(EMPLEADO_ID)
;

ALTER TABLE AREA_REVISOR ADD CONSTRAINT RefAREA_DE_INTERES16 
    FOREIGN KEY ("AREA DE INT_ID")
    REFERENCES "AREA DE INTERES"("AREA DE INT_ID")
;


-- 
-- TABLE: ARTICULO 
--

ALTER TABLE ARTICULO ADD CONSTRAINT RefAREA_DE_INTERES6 
    FOREIGN KEY ("AREA DE INT_ID")
    REFERENCES "AREA DE INTERES"("AREA DE INT_ID")
;

ALTER TABLE ARTICULO ADD CONSTRAINT RefEDITOR21 
    FOREIGN KEY (EDITOR_ID)
    REFERENCES EDITOR(EMPLEADO_ID)
;

ALTER TABLE ARTICULO ADD CONSTRAINT RefSTATUS28 
    FOREIGN KEY (STATUS_ID)
    REFERENCES STATUS(STATUS_ID)
;


-- 
-- TABLE: AUTOR_ARTICULO 
--

ALTER TABLE AUTOR_ARTICULO ADD CONSTRAINT RefAUTOR4 
    FOREIGN KEY (AUTOR_ID)
    REFERENCES AUTOR(AUTOR_ID)
;

ALTER TABLE AUTOR_ARTICULO ADD CONSTRAINT RefARTICULO5 
    FOREIGN KEY (ARTICULO_ID)
    REFERENCES ARTICULO(ARTICULO_ID)
;


-- 
-- TABLE: EDITOR 
--

ALTER TABLE EDITOR ADD CONSTRAINT RefEMPLEADO13 
    FOREIGN KEY (EMPLEADO_ID)
    REFERENCES EMPLEADO(EMPLEADO_ID)
;


-- 
-- TABLE: HISTORICO 
--

ALTER TABLE HISTORICO ADD CONSTRAINT RefSTATUS26 
    FOREIGN KEY (STATUS_ID)
    REFERENCES STATUS(STATUS_ID)
;

ALTER TABLE HISTORICO ADD CONSTRAINT RefARTICULO29 
    FOREIGN KEY (ARTICULO_ID)
    REFERENCES ARTICULO(ARTICULO_ID)
;


-- 
-- TABLE: PDF 
--

ALTER TABLE PDF ADD CONSTRAINT RefARTICULO30 
    FOREIGN KEY (ARTICULO_ID)
    REFERENCES ARTICULO(ARTICULO_ID)
;


-- 
-- TABLE: PUBLICACION_ARTICULO 
--

ALTER TABLE PUBLICACION_ARTICULO ADD CONSTRAINT RefARTICULO8 
    FOREIGN KEY (ARTICULO_ID)
    REFERENCES ARTICULO(ARTICULO_ID)
;

ALTER TABLE PUBLICACION_ARTICULO ADD CONSTRAINT RefPUBLICACION9 
    FOREIGN KEY (PUBLICACION_ID)
    REFERENCES PUBLICACION(PUBLICACION_ID)
;


-- 
-- TABLE: PUBLICACION_SUSCRIPTOR 
--

ALTER TABLE PUBLICACION_SUSCRIPTOR ADD CONSTRAINT RefSUSCRIPTOR23 
    FOREIGN KEY (SUSCRIPTOR_ID)
    REFERENCES SUSCRIPTOR(SUSCRIPTOR_ID)
;

ALTER TABLE PUBLICACION_SUSCRIPTOR ADD CONSTRAINT RefPUBLICACION24 
    FOREIGN KEY (PUBLICACION_ID)
    REFERENCES PUBLICACION(PUBLICACION_ID)
;


-- 
-- TABLE: REVISADO_ARTICULO 
--

ALTER TABLE REVISADO_ARTICULO ADD CONSTRAINT RefREVISOR17 
    FOREIGN KEY (REVISOR_ID)
    REFERENCES REVISOR(EMPLEADO_ID)
;

ALTER TABLE REVISADO_ARTICULO ADD CONSTRAINT RefARTICULO18 
    FOREIGN KEY (ARTICULO_ID)
    REFERENCES ARTICULO(ARTICULO_ID)
;


-- 
-- TABLE: REVISOR 
--

ALTER TABLE REVISOR ADD CONSTRAINT RefEMPLEADO14 
    FOREIGN KEY (EMPLEADO_ID)
    REFERENCES EMPLEADO(EMPLEADO_ID)
;


